### ISSUE TITLE
Wrong PHP_BINDIR path with Cygwin and WAMP

### ISSUE THREAD

**Issue by rootpd** [toriphes/yii2-console-runner#1]
When using CygWin in combination with WAMP, value of `PHP_BINDIR` is always `c:\php` which is wrong. I'm missing a possibility to configure this to whatever the need can be. Similar to `yiiscript` attribute.

**Comment by toriphes** [comment]
Thank you for your feedback.
I think this commit will solve the problem

f799540da6a0847e278bd1b2dd6e5a1e010817e8

**Comment by rootpd** [comment]
:+1: thanks!
