### ISSUE TITLE
 Apply the above migrations? (yes|no) [no]:

### ISSUE THREAD

**Issue by Aibric** [toriphes/yii2-console-runner#3]
$runner = new Runner();
$runner->run('migrate', $output);
echo $output;

Returns the following data:

Yii Migration Tool (based on Yii v2.0.11) Total 3 new migrations to be applied: m130524_201442_init m170503_053007_user m170503_054604_abc Apply the above migrations? (yes|no) [no]:

**Comment by toriphes** [comment]
Try adding `--interactive=0` option:
```php
<?php
$runner = new Runner();
$runner->run('migrate --interactive=0', $output);
echo $output;
```

**Comment by Aibric** [comment]
thank you @toriphes .
