### ISSUE TITLE
The change in getPHPExecutable brokes the extension

### ISSUE THREAD

**Issue by diegoparkingdoor** [toriphes/yii2-console-runner#6]
Now that getPHPExecutable uses PHP_BINARY the extension is broken for us (we run nginx over linux), as that constant returns the php-fpm binary.

**Comment by toriphes** [comment]
Thanks for the feedback, Try update to the last release.

If it doesn't work you can supply the `phpexec` property to the component config.

**Comment by diegoparkingdoor** [comment]
Thank you! We were already implementing that workaround, but now we can go back to regular usage with you last version :)
